//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppRunner.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AppRunner.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppRunner.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Common_Add {
            get {
                return ResourceManager.GetString("Common.Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Common_Cancel {
            get {
                return ResourceManager.GetString("Common.Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Common_Error {
            get {
                return ResourceManager.GetString("Common.Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string Common_No {
            get {
                return ResourceManager.GetString("Common.No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string Common_OK {
            get {
                return ResourceManager.GetString("Common.OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Common_Yes {
            get {
                return ResourceManager.GetString("Common.Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arguments.
        /// </summary>
        internal static string Label_Arguments {
            get {
                return ResourceManager.GetString("Label.Arguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command line arguments.
        /// </summary>
        internal static string Label_CommandLineArguments {
            get {
                return ResourceManager.GetString("Label.CommandLineArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t create window.
        /// </summary>
        internal static string Label_CreateNoWindow {
            get {
                return ResourceManager.GetString("Label.CreateNoWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Label_Description {
            get {
                return ResourceManager.GetString("Label.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display name.
        /// </summary>
        internal static string Label_DisplayName {
            get {
                return ResourceManager.GetString("Label.DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environment.
        /// </summary>
        internal static string Label_Environment {
            get {
                return ResourceManager.GetString("Label.Environment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environment variables.
        /// </summary>
        internal static string Label_EnvironmentVariables {
            get {
                return ResourceManager.GetString("Label.EnvironmentVariables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name.
        /// </summary>
        internal static string Label_FileName {
            get {
                return ResourceManager.GetString("Label.FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name or path.
        /// </summary>
        internal static string Label_FileNameOrPath {
            get {
                return ResourceManager.GetString("Label.FileNameOrPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Label_Name {
            get {
                return ResourceManager.GetString("Label.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run as Administrator.
        /// </summary>
        internal static string Label_RunAsAdministrator {
            get {
                return ResourceManager.GetString("Label.RunAsAdministrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use ShellExecute.
        /// </summary>
        internal static string Label_UseShellExecute {
            get {
                return ResourceManager.GetString("Label.UseShellExecute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working directory.
        /// </summary>
        internal static string Label_WorkingDirectory {
            get {
                return ResourceManager.GetString("Label.WorkingDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Menu_Edit {
            get {
                return ResourceManager.GetString("Menu.Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run.
        /// </summary>
        internal static string Menu_Run {
            get {
                return ResourceManager.GetString("Menu.Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run as Administrator.
        /// </summary>
        internal static string Menu_RunAsAdministrator {
            get {
                return ResourceManager.GetString("Menu.RunAsAdministrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run with.
        /// </summary>
        internal static string Menu_RunWithEnvironment {
            get {
                return ResourceManager.GetString("Menu.RunWithEnvironment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to run application.
        /// </summary>
        internal static string Message_FailedToRunApplication {
            get {
                return ResourceManager.GetString("Message.FailedToRunApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string PageName_About {
            get {
                return ResourceManager.GetString("PageName.About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applications.
        /// </summary>
        internal static string PageName_Applications {
            get {
                return ResourceManager.GetString("PageName.Applications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environments.
        /// </summary>
        internal static string PageName_Environments {
            get {
                return ResourceManager.GetString("PageName.Environments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string PageName_Settings {
            get {
                return ResourceManager.GetString("PageName.Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There&apos;s nothing here.
        /// </summary>
        internal static string Tips_ThereIsNothingHere {
            get {
                return ResourceManager.GetString("Tips.ThereIsNothingHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Application.
        /// </summary>
        internal static string Title_AddNewApplication {
            get {
                return ResourceManager.GetString("Title.AddNewApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Environment.
        /// </summary>
        internal static string Title_AddNewEnvironment {
            get {
                return ResourceManager.GetString("Title.AddNewEnvironment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Application.
        /// </summary>
        internal static string Title_EditApplication {
            get {
                return ResourceManager.GetString("Title.EditApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Environment.
        /// </summary>
        internal static string Title_EditEnvironment {
            get {
                return ResourceManager.GetString("Title.EditEnvironment", resourceCulture);
            }
        }
    }
}
