//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppRunner.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AppRunner.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Customize environment variables, file maps, and use them to launch applications on the fly. 的本地化字符串。
        /// </summary>
        internal static string AppDescription {
            get {
                return ResourceManager.GetString("AppDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AppRunner 的本地化字符串。
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export 的本地化字符串。
        /// </summary>
        internal static string Button_Export {
            get {
                return ResourceManager.GetString("Button.Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import 的本地化字符串。
        /// </summary>
        internal static string Button_Import {
            get {
                return ResourceManager.GetString("Button.Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add 的本地化字符串。
        /// </summary>
        internal static string Common_Add {
            get {
                return ResourceManager.GetString("Common.Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        internal static string Common_Cancel {
            get {
                return ResourceManager.GetString("Common.Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Default 的本地化字符串。
        /// </summary>
        internal static string Common_Default {
            get {
                return ResourceManager.GetString("Common.Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error 的本地化字符串。
        /// </summary>
        internal static string Common_Error {
            get {
                return ResourceManager.GetString("Common.Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No 的本地化字符串。
        /// </summary>
        internal static string Common_No {
            get {
                return ResourceManager.GetString("Common.No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 None 的本地化字符串。
        /// </summary>
        internal static string Common_None {
            get {
                return ResourceManager.GetString("Common.None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OK 的本地化字符串。
        /// </summary>
        internal static string Common_OK {
            get {
                return ResourceManager.GetString("Common.OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select 的本地化字符串。
        /// </summary>
        internal static string Common_Select {
            get {
                return ResourceManager.GetString("Common.Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 View 的本地化字符串。
        /// </summary>
        internal static string Common_View {
            get {
                return ResourceManager.GetString("Common.View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Yes 的本地化字符串。
        /// </summary>
        internal static string Common_Yes {
            get {
                return ResourceManager.GetString("Common.Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Working directory when working directory was not specified or not exist 的本地化字符串。
        /// </summary>
        internal static string Description_ApplicationDefaultWorkingDirectory {
            get {
                return ResourceManager.GetString("Description.ApplicationDefaultWorkingDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import or export configuration 的本地化字符串。
        /// </summary>
        internal static string Description_Configuration {
            get {
                return ResourceManager.GetString("Description.Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Application default working directory 的本地化字符串。
        /// </summary>
        internal static string Label_ApplicationDefaultWorkingDirectory {
            get {
                return ResourceManager.GetString("Label.ApplicationDefaultWorkingDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Application Information 的本地化字符串。
        /// </summary>
        internal static string Label_ApplicationInformation {
            get {
                return ResourceManager.GetString("Label.ApplicationInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Arguments 的本地化字符串。
        /// </summary>
        internal static string Label_Arguments {
            get {
                return ResourceManager.GetString("Label.Arguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Author 的本地化字符串。
        /// </summary>
        internal static string Label_Author {
            get {
                return ResourceManager.GetString("Label.Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Command line arguments 的本地化字符串。
        /// </summary>
        internal static string Label_CommandLineArguments {
            get {
                return ResourceManager.GetString("Label.CommandLineArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Configuration 的本地化字符串。
        /// </summary>
        internal static string Label_Configuration {
            get {
                return ResourceManager.GetString("Label.Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Don&apos;t create window 的本地化字符串。
        /// </summary>
        internal static string Label_CreateNoWindow {
            get {
                return ResourceManager.GetString("Label.CreateNoWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Description 的本地化字符串。
        /// </summary>
        internal static string Label_Description {
            get {
                return ResourceManager.GetString("Label.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Display name 的本地化字符串。
        /// </summary>
        internal static string Label_DisplayName {
            get {
                return ResourceManager.GetString("Label.DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Environment 的本地化字符串。
        /// </summary>
        internal static string Label_Environment {
            get {
                return ResourceManager.GetString("Label.Environment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Environment variables 的本地化字符串。
        /// </summary>
        internal static string Label_EnvironmentVariables {
            get {
                return ResourceManager.GetString("Label.EnvironmentVariables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File maps 的本地化字符串。
        /// </summary>
        internal static string Label_FileMaps {
            get {
                return ResourceManager.GetString("Label.FileMaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File name 的本地化字符串。
        /// </summary>
        internal static string Label_FileName {
            get {
                return ResourceManager.GetString("Label.FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File name or path 的本地化字符串。
        /// </summary>
        internal static string Label_FileNameOrPath {
            get {
                return ResourceManager.GetString("Label.FileNameOrPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Group 的本地化字符串。
        /// </summary>
        internal static string Label_Group {
            get {
                return ResourceManager.GetString("Label.Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 License 的本地化字符串。
        /// </summary>
        internal static string Label_License {
            get {
                return ResourceManager.GetString("Label.License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name 的本地化字符串。
        /// </summary>
        internal static string Label_Name {
            get {
                return ResourceManager.GetString("Label.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Run as Administrator 的本地化字符串。
        /// </summary>
        internal static string Label_RunAsAdministrator {
            get {
                return ResourceManager.GetString("Label.RunAsAdministrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Third-party libraries 的本地化字符串。
        /// </summary>
        internal static string Label_ThirdPartyLibraries {
            get {
                return ResourceManager.GetString("Label.ThirdPartyLibraries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use ShellExecute 的本地化字符串。
        /// </summary>
        internal static string Label_UseShellExecute {
            get {
                return ResourceManager.GetString("Label.UseShellExecute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Version 的本地化字符串。
        /// </summary>
        internal static string Label_Version {
            get {
                return ResourceManager.GetString("Label.Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 View license 的本地化字符串。
        /// </summary>
        internal static string Label_ViewLicense {
            get {
                return ResourceManager.GetString("Label.ViewLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Working directory 的本地化字符串。
        /// </summary>
        internal static string Label_WorkingDirectory {
            get {
                return ResourceManager.GetString("Label.WorkingDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        internal static string Menu_Delete {
            get {
                return ResourceManager.GetString("Menu.Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Deploy 的本地化字符串。
        /// </summary>
        internal static string Menu_Deploy {
            get {
                return ResourceManager.GetString("Menu.Deploy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Duplicate 的本地化字符串。
        /// </summary>
        internal static string Menu_Duplicate {
            get {
                return ResourceManager.GetString("Menu.Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit 的本地化字符串。
        /// </summary>
        internal static string Menu_Edit {
            get {
                return ResourceManager.GetString("Menu.Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Run 的本地化字符串。
        /// </summary>
        internal static string Menu_Run {
            get {
                return ResourceManager.GetString("Menu.Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Run as Administrator 的本地化字符串。
        /// </summary>
        internal static string Menu_RunAsAdministrator {
            get {
                return ResourceManager.GetString("Menu.RunAsAdministrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Run with 的本地化字符串。
        /// </summary>
        internal static string Menu_RunWithEnvironment {
            get {
                return ResourceManager.GetString("Menu.RunWithEnvironment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An error occurred while performing file mapping on the target application 的本地化字符串。
        /// </summary>
        internal static string Message_AnErrorOccurredWhilePerformingFileMappingOnTheTargetApplication {
            get {
                return ResourceManager.GetString("Message.AnErrorOccurredWhilePerformingFileMappingOnTheTargetApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 App file name can not be empty 的本地化字符串。
        /// </summary>
        internal static string Message_AppFileNameCanNotBeEmpty {
            get {
                return ResourceManager.GetString("Message.AppFileNameCanNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to export configuration 的本地化字符串。
        /// </summary>
        internal static string Message_FailedToExportConfiguration {
            get {
                return ResourceManager.GetString("Message.FailedToExportConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to export configuration, please check if you currently have access rights to the target path. 的本地化字符串。
        /// </summary>
        internal static string Message_FailedToExportConfigurationPleaseCheckIfYouCurrentlyHaveAccessRightsToTargetPath {
            get {
                return ResourceManager.GetString("Message.FailedToExportConfigurationPleaseCheckIfYouCurrentlyHaveAccessRightsToTar" +
                        "getPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to import configuration 的本地化字符串。
        /// </summary>
        internal static string Message_FailedToImportConfiguration {
            get {
                return ResourceManager.GetString("Message.FailedToImportConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to import configuration, please check if the file format is correct. 的本地化字符串。
        /// </summary>
        internal static string Message_FailedToImportConfigurationPleaseCheckIfTheFileFormatIsCorrect {
            get {
                return ResourceManager.GetString("Message.FailedToImportConfigurationPleaseCheckIfTheFileFormatIsCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to run application 的本地化字符串。
        /// </summary>
        internal static string Message_FailedToRunApplication {
            get {
                return ResourceManager.GetString("Message.FailedToRunApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        internal static string PageName_About {
            get {
                return ResourceManager.GetString("PageName.About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Applications 的本地化字符串。
        /// </summary>
        internal static string PageName_Applications {
            get {
                return ResourceManager.GetString("PageName.Applications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Environments 的本地化字符串。
        /// </summary>
        internal static string PageName_Environments {
            get {
                return ResourceManager.GetString("PageName.Environments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        internal static string PageName_Settings {
            get {
                return ResourceManager.GetString("PageName.Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name=Value 的本地化字符串。
        /// </summary>
        internal static string Placeholder_EnvironmentVariables {
            get {
                return ResourceManager.GetString("Placeholder.EnvironmentVariables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SourceFile&gt;DestinationFile 的本地化字符串。
        /// </summary>
        internal static string Placeholder_FileMaps {
            get {
                return ResourceManager.GetString("Placeholder.FileMaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There&apos;s nothing here 的本地化字符串。
        /// </summary>
        internal static string Tips_ThereIsNothingHere {
            get {
                return ResourceManager.GetString("Tips.ThereIsNothingHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add New Application 的本地化字符串。
        /// </summary>
        internal static string Title_AddNewApplication {
            get {
                return ResourceManager.GetString("Title.AddNewApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add New Environment 的本地化字符串。
        /// </summary>
        internal static string Title_AddNewEnvironment {
            get {
                return ResourceManager.GetString("Title.AddNewEnvironment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit Application 的本地化字符串。
        /// </summary>
        internal static string Title_EditApplication {
            get {
                return ResourceManager.GetString("Title.EditApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit Environment 的本地化字符串。
        /// </summary>
        internal static string Title_EditEnvironment {
            get {
                return ResourceManager.GetString("Title.EditEnvironment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export configuration 的本地化字符串。
        /// </summary>
        internal static string Title_ExportConfiguration {
            get {
                return ResourceManager.GetString("Title.ExportConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import configuration 的本地化字符串。
        /// </summary>
        internal static string Title_ImportConfiguration {
            get {
                return ResourceManager.GetString("Title.ImportConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Group 的本地化字符串。
        /// </summary>
        internal static string Tooltip_SelectGroup {
            get {
                return ResourceManager.GetString("Tooltip.SelectGroup", resourceCulture);
            }
        }
    }
}
